version: '3'

services:
  php:
    build: .
    ports:
      - "82:80"
    volumes:
      - ./www:/var/www/html
    networks:
        - app_net
            
            
networks:
    app_net:
        driver: bridge
